### ISSUE TITLE
Acaia Pearl shows up as PROCHBT001 in bluetooth devices

### ISSUE THREAD

**Issue by sidequestboy** [lucapinello/pyacaia#3]
`find_acaia_devices` fails to find my Acaia Pearl because it shows up as "PROCHBT001" ... I'm not sure why this is, since I suppose yours appears as "ACAIA...", and the support documents from Acaia say it should show up as "Pearl". In any case, my Acaia android app seems to identify and auto-connect with it correctly despite its name.

**Comment by lucapinello** [comment]
In your specific case you can still use the MAC address, it should work!

**Comment by sidequestboy** [comment]
Yeah you're right, the other functions work. Just wanted to document this issue in case others encounter it.

**Comment by lucapinello** [comment]
No problem! If you don't mind to share what are you building with it?

**Comment by sidequestboy** [comment]
I'm putting together a raspberry pi + sensors project for use in the cafe I work in. It's an investigation into the effect of grinder temperature and other variables on espresso parameters and grinder settings - I'm using this library to log periodic espresso calibration shots throughout the course of a day (:

**Comment by lucapinello** [comment]
Very cool! if you post it on GitHub please let me know, I love this kind of
stuff :)
